### ISSUE TITLE
Seperate git checkouts are forcing retransmitting to many files

### ISSUE THREAD

**Issue by rodja** [zauberzeug/livesync#2]
Because [git does not set the modification time](https://softwareengineering.stackexchange.com/questions/350403/why-doesnt-git-set-the-file-time) to the last commit time, every checkout has different modification times for the same files. This results in a too-large transfer when `livesync` is first started with another checkout. For example if two developers work on the same target at different times.

Maybe LiveSync can incorporate `git-restore-mtime` (https://github.com/MestreLion/git-tools/blob/main/git-restore-mtime and https://stackoverflow.com/a/13284229/364388) or a simpler version like https://stackoverflow.com/a/36243002/364388.

- [x] Try out `-c`
- [x] How to trigger the auto-reload without changing a file?
- [x] Implement `--on-change` argument
- [x] Review

**Comment by rodja** [comment]
Maybe the rsync option `-c` is all we need: https://serverfault.com/a/200683/959437

**Comment by falkoschindler** [comment]
Yes, `-c` or `--checksum` works. But we need to clarify
- [ ] how to trigger the auto-reload without changing a file?

Even a post-sync-hook wouldn't work, since there is nothing to sync.

**Comment by rodja** [comment]
>  Even a post-sync-hook wouldn't work, since there is nothing to sync.

Well, the file-change should be detected with `fswatch`. So this could depend on #1.

**Comment by rodja** [comment]
We will introduce a parameter to define a command which should be executed on the remote after an change occured:
 
   `livesync --on-change="touch main.py" <remote target>`

Of course for this to work we must first solve #1.

**Comment by rodja** [comment]
I've created some testing infrastructure and build a test for this feature. I also added the execution of the on-change command after the initial sync.

**Comment by rodja** [comment]
Fixed in [0.2.1](https://github.com/zauberzeug/livesync/releases/tag/0.2.1).
