### ISSUE TITLE
Livesync does not ignore changing .git folder on Windows 11 WSL

### ISSUE THREAD

**Issue by SeaTechRC** [zauberzeug/livesync#22]
Hello.

When using the Windows 11 WSL, it seems that the .git folder is not ignored.
![image](https://github.com/zauberzeug/livesync/assets/153106523/fa96a40c-397c-4e86-888a-448955ce2216)

I added some debug output to give a bit more information:
![image](https://github.com/zauberzeug/livesync/assets/153106523/b0d962ac-66e9-4ca1-880e-dd5e2a8e7ca4)

even though .git/ is part of the .syncignore for the field_friend folder, changes to the .git folder of field_friend are still reported.

**Comment by SeaTechRC** [comment]
![image](https://github.com/zauberzeug/livesync/assets/153106523/4ffb4b85-5b4c-4b37-aa36-6e8ec99d971f)

here is also a list of the compiled regex patterns

**Comment by SeaTechRC** [comment]
Here is also a list of the compiled regex patterns

**Comment by SeaTechRC** [comment]
On further inspection, it seems as if watchfiles reports the git folder without the / at the end.
It could be that watchfiles reports folders differently on WSL (or perhaps ubuntu, since ubuntu is running in WSL).

Another possibility I considered is that changes in the .git folder happen every time the summary for the folder is made because of a quirk with the way the mounting of the C: drive works in WSL (I the creation, modification and access time reported by os.stat() changes everytime).

It could also be the case that pathspec compiles the wrong regex for the pattern, since (I think) the (?<ps_d>/) group is not optional. This could how could however be correct, since the documentation for git says:

> If there is a separator at the end of the pattern then the pattern will only match directories, otherwise the pattern can match both files and directories.
[https://git-scm.com/docs/gitignore](url)

This would suggest that the pattern cannot simply be compiled to a regex (if watchfiles is not supposed to report directories with a slash at the end).

**Comment by rodja** [comment]
Ok, I can reproduce the issue on Mac/Linux as follows:

1. start LiveSync in an empty directory
2. create a folder which is in the .syncignore file (for example `.git/`)
3. you will see that it is still synced -- and following `touch` commands (which update the `mtime`) will retrigger a sync
4. expectation: the folder is not synced because it is in the `.syncignore` file
5. observation: due to the trailing slash in the folder spec `pathspec` only matches everything inside the folder, not the folder itself
