### ISSUE TITLE
Specify subfolder on target

### ISSUE THREAD

**Issue by denniswittich** [zauberzeug/livesync#8]
It would be useful in some scenarios to specify a subfolder on the target device to clone to. E.g. with an argument:

Running `livesync project --subfolder a_folder` from "project" folder on the local device should sync "local:project" to "remote:a_folder/project"

**Comment by rodja** [comment]
Sounds good. Maybe `--target-root` would be a better name. Because we can sync multiple projects which will be placed side by side. Default would be the home directory.
Would you like to create a pull request?

**Comment by falkoschindler** [comment]
We just released v0.2.2 with the new `--target-root` argument.
