### ISSUE TITLE
Improve API for excluding files from synchronization

### ISSUE THREAD

**Issue by falkoschindler** [zauberzeug/livesync#9]
This is the current implementation for excluding files from synchronization:
```py
def get_excludes(self) -> List[str]:
    return ['.git/', '__pycache__/', '.DS_Store', '*.tmp', '.env'] + \
        self._parse_ignore_file(self.local_path / '.syncignore') + \
        self._parse_ignore_file(self.local_path / '.gitignore')
```

From the user's perspective it might be surprising that so many files are already ignored. But even though it looks like all git-ignored files are ignored, only the .gitignore in the current working directory is considered. Besides that, it is impossible to sync a .env file in case the user would like to do so.

Therefore, I would like to make it more flexible and predictable by
1. ignoring the .gitignore file and
2. making the array of other excludes configurable via argparse.

**Comment by falkoschindler** [comment]
Ok, I introduced an "ignore" argument:
```
--ignore [IGNORE ...]
      comma-separated list of paths to ignore (default: .git/, __pycache__/, .DS_Store, *.tmp, .env)
```
It seemed to be easiest to define it as a comma-separated list of paths. An array would be trickier to manipulate via command-line arguments.

Now I just wonder how to handle .syncignore files in combination with the "ignore" argument:
1. Should the file be additive? Then we would need to additionally write `--ignore ""` to _replace_ the default ignores with the .syncignore file.
2. Or should a .syncignore file automatically replace the `--ignore` argument? Then we would need to add all default ignores to the file if we just want to extend the list.

The API and design decisions for such a tiny program turn out surprisingly complicated...

**Comment by rodja** [comment]
As an alternative you could argue that `.syncignore` is not needed at all. If you want to specify special set of ignores for your project you can always create a `sync.sh` script.

**Comment by falkoschindler** [comment]
We decided to remove the `--include` argument, only use the `.syncignore` file and create it with default values if it doesn't exist yet.
